export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FALL = "ALL_PRODUCTS_FALL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
